"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import pytz
pytz.zoneinfo = pytz.tzinfo
pytz.zoneinfo.UTC = pytz.UTC

from setuptools import setup
from csversion import CIRCUITSCAPE_VER, CIRCUITSCAPE_AUTHOR, CIRCUITSCAPE_EMAIL

INCLUDES = []
PACKAGES = ['wx', 'wxversion', 'PythonCard', 'numpy', 'scipy', 'pyamg']

DATA_FILES = ['cs_gui.rsrc.py', 'verify.py', 'cs_logo.jpg', 
              'verify', 'verify/1', 'verify/2', 'verify/3', 'verify/4', 'verify/5', 'verify/6', 'verify/7', 'verify/8']
OPTIONS = {'includes': PACKAGES, 
           'argv_emulation' : True,
           'plist': { 'CFBundleIdentifier': 'Circuitscape',
                      'CFBundleGetInfoString': 'Circuitscape: Circuit theoretic landscape connectivity',
                      'CFBundleDisplayName': 'Circuitscape',
                      'CFBundleIconFile': 'cs_logo.jpg',
                      'CFBundleIdentifier': 'org.circuitscape',
                      'CFBundleName': 'Circuitscape'
                     }
           }
#Now also compile cs_run.py.  compiling it first ensures that dependencies needed for cs_gui also included.
# setup(
#     app=['cs_run.py'],
#     setup_requires=['py2app'],
#     data_files=DATA_FILES,
#     options={'py2app': OPTIONS},
#     version=CIRCUITSCAPE_VER,
#     author=CIRCUITSCAPE_AUTHOR,
#     author_email=CIRCUITSCAPE_EMAIL
# )

setup(
    app=['cs_gui.py'],
    setup_requires=['py2app'],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    version=CIRCUITSCAPE_VER,
    author=CIRCUITSCAPE_AUTHOR,
    author_email=CIRCUITSCAPE_EMAIL
    )
