"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2exe
"""

import os
import py2exe
from distutils.core import setup

#INCLUDES = []
INCLUDES =[]
PACKAGES = ['PythonCard', 'wx', 'numpy', 'scipy', 'pyamg',"scipy.io.matlab.streams"]

DATA_FILES = ['cs_gui.rsrc.py', 'cs_verify.py', 'gapdt.py', 'cs_compute.py', 'cs_util.py', 'cs_logo.jpg', 'cs_logo.ico']
OPTIONS = {'includes': PACKAGES}

#Now also compile cs_run.py.  compiling it first ensures that dependencies needed for cs_gui also included.
setup(
    console=['cs_run.py'],
    data_files=DATA_FILES,
    options={'py2exe': OPTIONS},
    version='3.5.8',
    author='Brad H. McRae and Viral B. Shah',
    author_email='mcrae@circuitscape.org'
)
setup(
    console=['cs_gui.py'],
    data_files=DATA_FILES,
    options={'py2exe': OPTIONS},
    version='3.5.6',
    author='Brad H. McRae and Viral B. Shah',
    author_email='mcrae@circuitscape.org'
)


