"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2exe
"""

# experimental code for linkage mapper interface BHM 2011-09-04

import os
import py2exe
from distutils.core import setup

#INCLUDES = []
INCLUDES =[]
PACKAGES = ['numpy', 'scipy', 'pyamg',"scipy.io.matlab.streams"]

DATA_FILES = ['gapdt.py', 'cs_compute.py', 'cs_util.py']
OPTIONS = {'includes': PACKAGES}

setup(
    console=['cs_run.py'],
    data_files=DATA_FILES,
    options={'py2exe': OPTIONS},
    version='3.5.5',
    author='Brad H. McRae and Viral B. Shah',
    author_email='mcrae@circuitscape.org'
)
